desc "Add Branch keys and Universal Link domains to BranchPluginExample"
lane :test do
  setup_branch live_key: "key_live_feebgAAhbH9Tv85H5wLQhpdaefiZv5Dv",
               test_key: "key_test_hdcBLUy1xZ1JD0tKg7qrLcgirFmPPVJc",
     app_link_subdomain: "bnctestbed",
              xcodeproj: "BranchPluginExample/BranchPluginExample.xcodeproj"
end
