#!/bin/bash

if [[ "`uname -s`" != "Darwin" ]] ; then
  echo "Error: macOS required"
  exit -1
fi

# https://rvm.io/workflow/scripting
# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  echo "RVM not detected. Using local Ruby environment."
fi

PATH=${PATH}:/usr/local/bin

if [[ -s "`which yarn`" ]] ; then
  HAVE_YARN=1
  yarn
else
  echo "yarn not detected. Using npm install."
  npm install
fi

bundle check || bundle install

bundle exec fastlane android test
bundle exec fastlane ios test

if [[ "$HAVE_YARN" = 1 ]] ; then
  yarn lint
  yarn test
else
  npm run lint
  npm test
fi

exit 0
