platform :ios, "9.0"

target "NativeTests" do
  pod "React", path: "../../node_modules/react-native", subspecs: %w[Core CxxBridge DevSupport RCTNetwork]
  pod "yoga", path: "../../node_modules/react-native/ReactCommon/yoga"
  pod 'Folly', podspec: '../../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod "react-native-branch", path: "../.."
end

target "NativeTestsTests" do
  pod "OCMock"
end
