platform :ios, "8.0"

target "NativeTests" do
  pod "React", path: "../../node_modules/react-native"
  pod "Yoga", path: "../../node_modules/react-native/ReactCommon/yoga"
  pod "react-native-branch", path: "../.."
  pod "Branch-SDK", path: "../../ios"
end

target "NativeTestsTests" do
  pod "OCMock"
end
