fastlane_version "2.27"

desc "Update Branch configuration"
lane :update_branch do
  setup_branch(
    android_project_path: "android",
    xcodeproj: "ios/webview_tutorial.xcodeproj"
  )
end

desc "Validate Universal Links in iOS project"
lane :validate do
  validate_universal_links xcodeproj: "ios/webview_example.xcodeproj"
end
