import React from 'react';

import { YellowBox } from 'react-native';

// disable a warning generated by react-navigation
YellowBox.ignoreWarnings([
  'Warning: componentWillReceiveProps',
]);

import { createAppContainer, createStackNavigator } from 'react-navigation';
import Article from './Article';
import ArticleList from './ArticleList';

const RootNavigator = createStackNavigator({
  Home: {
    screen: ArticleList,
  },
  Article: {
    screen: Article,
  }
});

export default createAppContainer(RootNavigator);
