fastlane_version "2.27"

desc "Update Branch configuration"
lane :update_branch do
  setup_branch(
    xcodeproj: "testbed_native_ios.xcodeproj",
    update_bundle_and_team_ids: true,
    remove_existing_domains: true
  )
end

desc "Validate Universal Links in iOS project"
lane :validate do
  validate_universal_links xcodeproj: "testbed_native_ios.xcodeproj"
end
