platform :ios, "9.0"

pod "React",
  path: "node_modules/react-native",
  subspecs: %w{
    Core
    CxxBridge
    DevSupport
    RCTAnimation
    RCTImage
    RCTText
    RCTNetwork
    RCTWebSocket
  }
pod "yoga", path: "node_modules/react-native/ReactCommon/yoga"
pod "Folly", :podspec => "node_modules/react-native/third-party-podspecs/Folly.podspec"
pod "react-native-branch", path: "node_modules/react-native-branch"
pod "Branch-SDK", path: "node_modules/react-native-branch/ios"

target "testbed_native_ios"
project "testbed_native_ios", "Test-Debug" => :debug, "Test-Release" => :release
