import { transkeys } from './../translations/en';
export const ROUTES = {
    BRANCH_LIST_SCREEN: 'BRANCH_LIST_SCREEN',
    BRANCH_INPUT_SCREEN: 'BRANCH_INPUT_SCREEN',
    BRANCH_GENERATE_URL: 'BRANCH_GENERATE_URL',
    LOG_DISPLAY: 'LOG_DISPLAY',
    MESSAGE_DISPLAY: 'MESSAGE_DISPLAY',
    ADD_META_DATA: 'ADD_META_DATA',
    READ_DEEP_LINK: 'READ_DEEP_LINK',
    NOTIFICATION_DETAILS: 'NOTIFICATION_DETAILS',
    NAVIGATE_TO_CONTENT: 'NAVIGATE_TO_CONTENT',
    TRACK_CONTENT: 'TRACK_CONTENT',
    TRACK_CONTENT_EVENTS: 'TRACK_CONTENT_EVENTS',
    TRACK_CONTENT_RESPONSE: 'TRACK_CONTENT_RESPONSE',
};
export const testIds = {
    btnCreateContentReference: 'btnCreateContentReference',
    btnDisplayContent: 'btnDisplayContent',
    btnCreateDeepLink: 'btnCreateDeepLink',
    btnSendNotification: 'btnSendNotification',
    btnShareDeepLink: 'btnShareDeepLink',
    btnReadDeepLink: 'btnReadDeepLink',
    btnNavigateToContent: 'btnNavigateToContent',
    btnHandleLinks: 'btnHandleLinks',
    btnTrackUsers: 'btnTrackUsers',
    btnTrackContent: 'btnTrackContent',
    btnSubmit: 'btnSubmit',
    btnAddMetadata: 'btnAddMetadata',
    inputContentIdentifier: 'inputContentIdentifier',
    inputContentDescription: 'inputContentDescription',
    inputContentTitle: 'inputContentTitle',
    inputImageURL: 'inputImageURL',

    inputChannelName: 'inputChannelName',
    inputShareFeature: 'inputShareFeature',
    inputCampaignName: 'inputCampaignName',
    inputStageTestId: 'inputStageTestId',
    inputDesktopURL: 'inputDesktopURL',
    inputAndroidURL: 'inputAndroidURL',
    inputIosURL: 'inputIosURL',
    inputAdditionalData: 'inputAdditionalData',
    inputAdditionalDataContent: 'inputAdditionalDataContent',
    inputCustomEventProperty1: 'inputCustomEventProperty1',
    inputCustomEventProperty2: 'inputCustomEventProperty2',

    messageDisplayContainer: 'messageDisplayContainer',
    messageDisplayHeaderText: 'messageDisplayHeaderText',
    messageDisplaySubtitle: 'messageDisplaySubtitle',
    serverLogs: 'txtServerLogs',
    messageDisplayBtnNext: 'messageDisplayBtnNext',
    textShortURL: 'txtShortURL',
    textLongURL: 'txtLongURL',
    webviewContainer: 'webviewContainer',
    btnEnableTracking: 'btnEnableTracking',
    btnOpenLink: 'btnOpenLink',
    readDeepLinkContainer: 'readDeepLinkContainer',
    notificationDisplayContainer: 'notificationDisplayContainer',
    notificationHeader: 'txtNotificationHeader',
    notificationMessage: 'txtNotificationMessage',
    btnNextNotification: 'btnNextNotification',
    txtSourceURL: 'txtSourceURL',
    modalContainer: 'modalContainer',
    modalButtonOkay: 'btnModalOkay',
    modalTitle: 'txtModalTitle',
    modalSubtitle: 'txtModalSubtitle',
    modalDivider: 'txtModalDivider',
    btnNavigateLink: 'btnNavigateLink',
    txtJsonTree: 'txtJsonTree',
    txtPropertiesHeader: 'txtPropertiesHeader',
    inputTransaction_id: 'inputTransaction_id',
    inputTransactionIdLyfeCycle: 'inputTransactionIdLyfeCycle',
    inputAlias: 'inputAlias',
    inputAliasContent: 'inputAliasContent',
    inputAliasCustomEvents: 'inputAliasCustomEvents',
    inputAliasLifeCycle: 'inputAliasLifeCycle',
    inputRevenue: 'inputRevenue',
    inputShipping: 'inputShipping',
    inputTax: 'inputTax',
    inputCoupan: 'inputCoupan',
    inputAffiliation: 'inputAffiliation',
    inputDescription: 'inputDescription',
    inputDescriptionContent: 'inputDescriptionContent',
    inputDescriptionLifeCycle: 'inputDescriptionLifeCycle',
    inputRegistrationID: 'inputRegistrationID',
    inputPurchase_loc: 'inputPurchase_loc',
    inputSearchQuery: 'inputSearchQuery',
    dropdownAvailability: 'dropdownAvailability',
    dropDownCurrency: 'dropDownCurrency',
    dropDownContentSchema: 'dropDownContentSchema',
    dropDownEvent: 'dropDownEvent',
    dropDownEventContent: 'dropDownEventContent',
    dropDownEventLifeCycle: 'dropDownEventLifeCycle',
    inputProductName: 'inputProductName',
    inputProductBrand: 'inputProductBrand',
    inputProductVariant: 'inputProductVariant',
    dropdownSupplyValue: 'dropdownSupplyValue',
    dropDownProductCondition: 'dropDownProductCondition',
    inputStreet: 'inputStreet',
    inputCity: 'inputCity',
    inputRegion: 'inputRegion',
    inputCountry: 'inputCountry',
    inputPostalCode: 'inputPostalCode',
    inputLattitude: 'inputLattitude',
    inputLongitude: 'inputLongitude',
    inputSKU: 'inputSKU',
    inputRatting: 'inputRatting',
    inputAverageRating: 'inputAverageRating',
    inputMaxRatting: 'inputMaxRatting',
    inputRattingCount: 'inputRattingCount',
    inputImageCaptions: 'inputImageCaptions',
    inputPrice: 'inputPrice',
    inputQuantity: 'inputQuantity',
    inputCustomMetadata: 'inputCustomMetadata',
    scrollContainer: 'scrollContainer',
    txtSdkParams: 'txtSdkParams',
    inputCustomEvent: 'inputCustomEvent',
    inputCustomData1: 'inputCustomData1',
    inputCustomData2: 'inputCustomData2',
};
export const NAVIGATION_PARAM = {
    ROUTES_CREATE_CONTENT_REFERENCE: 'ROUTES_CREATE_CONTENT_REFERENCE',
    ROUTE_DISPLAY_CONTENT: 'ROUTE_DISPLAY_CONTENT',
    ROUTE_CREATE_DEEP_LINK: 'ROUTE_CREATE_DEEP_LINK',
    ROUTE_SEND_NOTIFICATION: 'ROUTE_SEND_NOTIFICATION',
    ROUTE_SHARE_DEEPLINK: 'ROUTE_SHARE_DEEPLINK',
    ROUTE_READ_DEEP_LINK: 'ROUTE_READ_DEEP_LINK',
    ROUTE_NAVIGATE_CONTENT: 'ROUTE_NAVIGATE_CONTENT',
    ROUTE_HANDLE_DEEPLINK: 'ROUTE_HANDLE_DEEPLINK',
    ROUTE_TRACK_USER: 'ROUTE_TRACK_USER',
    ROUTE_TRACK_CONTENT: 'ROUTE_TRACK_CONTENT',
    ROUTE_ADD_META_DATA: 'ROUTE_ADD_META_DATA',
};
export const BRANCH_LIST_DATA = [
    {
        id: NAVIGATION_PARAM.ROUTES_CREATE_CONTENT_REFERENCE,
        name: 'Create Content Reference',
        testId: testIds.btnCreateContentReference,
    },
    {
        id: NAVIGATION_PARAM.ROUTE_CREATE_DEEP_LINK,
        name: 'Create Deep Link',
        testId: testIds.btnCreateDeepLink,
    },
    {
        id: NAVIGATION_PARAM.ROUTE_SEND_NOTIFICATION,
        name: 'Send Notification',
        testId: testIds.btnSendNotification,
    },
    {
        id: NAVIGATION_PARAM.ROUTE_SHARE_DEEPLINK,
        name: 'Share Deep Link',
        testId: testIds.btnShareDeepLink,
    },
    {
        id: NAVIGATION_PARAM.ROUTE_READ_DEEP_LINK,
        name: transkeys.readDeepLink,
        testId: testIds.btnReadDeepLink,
    },
    {
        id: NAVIGATION_PARAM.ROUTE_NAVIGATE_CONTENT,
        name: transkeys.navigateToContent,
        testId: testIds.btnNavigateToContent,
    },
    {
        id: NAVIGATION_PARAM.ROUTE_HANDLE_DEEPLINK,
        name: transkeys.handleLinkinApp,
        testId: testIds.btnHandleLinks,
    },
    {
        id: NAVIGATION_PARAM.ROUTE_TRACK_USER,
        name: 'Track User',
        testId: testIds.btnTrackUsers,
    },
    {
        id: NAVIGATION_PARAM.ROUTE_TRACK_CONTENT,
        name: transkeys.trackContent,
        testId: testIds.btnTrackContent,
    },
];
export const TEST_USER_ID = 'qentelli_test_user';

export const ParamsType = {
    PARAMS: 'BranchSDK Response',
    LAST_PARAMS: 'BranchSDK lastParams',
    INSTALL_PARAMS: 'BranchSDK installParams',
    TRACK_CONTENT_RESPONSE: 'Track Content Response',
};
export const displayContent = {
    id: NAVIGATION_PARAM.ROUTE_DISPLAY_CONTENT,
    name: 'Display Content',
    testId: testIds.btnDisplayContent,
};
export const TRACK_CONTENT_TYPE = {
    COMMERCE: 'Commerce',
    CONTENT: 'Content',
    LIFECYCLE: 'Lifecycle',
    CUSTOM: 'Custom',
};
export const ContentMetadata = {
    $content_schema: '',
    $quantity: '',
    $price: '',
    $currency: '',
    $sku: '',
    $product_name: '',
    $product_brand: '',
    $product_category: '',
    $condition: '',
    $product_variant: '',
    $rating: '',
    $rating_average: '',
    $rating_count: '',
    $rating_max: '',
    $address_street: '',
    $address_city: '',
    $address_region: '',
    $address_country: '',
    $address_postal_code: '',
    $latitude: '',
    $longitude: '',
    $image_captions: '',
    Custom_Content_metadata_key1: '',
};
