pod "React", path: "node_modules/react-native", subspecs: [ "Core", "RCTAnimation", "RCTImage", "RCTText", "RCTNetwork", "RCTWebSocket" ]
pod "react-native-branch", path: "node_modules/react-native-branch"
# pod "Branch-SDK", path: "node_modules/react-native-branch/ios"
pod "Branch-SDK", path: "../../ios"

target "WebViewExample"
