name: appium-automation
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
env:
  ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  BROWSERSTACK_USER: ${{ secrets.BROWSER_STACK_USER }}
  BROWSERSTACK_KEY: ${{ secrets.BROWSER_STACK_KEY }}
jobs:  
  appium-automation-tests:
    name: appium-automation-tests
    runs-on: macos-latest
    steps:
      - name: Checkout SDK repo with testbed app
        uses: actions/checkout@v3
        with:
          path: sdk
          ref: SDK-1972-move-qentelli-automation-testbed
      # point to automation master branch by default
      - name: Checkout qa automation
        uses: actions/checkout@v3
        with:
          path: qa
          repository: BranchMetrics/qentelli-saas-sdk-testing-automation
          token: ${{ secrets.BRANCHLET_ACCESS_TOKEN_PUBLIC }}
          ref: SDK-1984-Merge-ReactNativeRepo
        # repo's gradle is configured to run on java 11
      - name: Setup java 11 for gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      # to reduce complexity, testbed app uses sdk as a project reference
      - name: Build testbed app for Android
        run: |
          cd sdk/branch-sdk-automation-testbed/
          npm install
          cd ./android
          ./gradlew assemble
          cd ../../
      - name: Upload APK to BrowserStack
        run: |
          response=$(curl -X POST https://api-cloud.browserstack.com/app-automate/upload -u "${{ secrets.BROWSER_STACK_USER }}:${{ secrets.BROWSER_STACK_KEY }}"  -F "file=@sdk/branch-sdk-automation-testbed/android/app/build/outputs/apk/debug/app-debug.apk")
          parsed=$(echo $response | jq ".app_url")
          echo "::add-mask::$parsed"
          echo "APP_URL=$parsed" >> "$GITHUB_ENV"
      - name: Execute automation
        run: |
          cd qa
          mvn clean test -DsuiteXMLFile=testng.xml -e -DInputFormat="json" -DInputFilePath="TestSelection_BrowserStack_Android_RN.json" -DUploadNewBuild="Yes"
                - name: Build testbed app for Android -DIS_RN_APP="true"
